services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:1401443038@localhost:3306/mychat
    depends_on:
      - mysql
    networks:
      - nest-mysql-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysqlroot
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nest-mysql-network

volumes:
  mysql-data:

networks:
  nest-mysql-network:
    driver: bridge